version: "3.9"
services:
  oracledb:
    init: true
    restart: always
    hostname: oracledb
    container_name: oracledb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1521:1521"
    env_file:
      - .env
    volumes:
      - ./oracle11g/:/docker-entrypoint-initdb.d/
      - ./data/:/data/
